export default [
  'Cheese Pizza',
  'Hamburger',
  'Cheeseburger',
  'Bacon Burger',
  'Bacon Cheeseburger',
  'Little Hamburger',
  'Little Cheeseburger',
  'Little Bacon Burger',
  'Little Bacon Cheeseburger',
  'Veggie Sandwich',
  'Cheese Veggie Sandwich',
  'Grilled Cheese',
  'Cheese Dog',
  'Bacon Dog',
  'Bacon Cheese Dog',
  'Pasta',
]
